[package]
name = "github-history"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minreq = { version = "2.11.0", features = ["https"] }
jzon = { version="0.12.5" } 
aes = { version = "0.8.3" }
